### ISSUE TITLE
Create discussion forum

### ISSUE THREAD

**Issue by brylie** [AngelSensorCommunityEdition/angel-sdk-community#2]
In order to facilitate asynchronous discussions, we can use an open discussion forum. Rather than hosting our own forum software, we might be able to connect with an existing community, such as the [OpenHealthHub](https://www.openhealthhub.org/). There is an existing [Open Medical Hardware](https://www.openhealthhub.org/t/open-hardware-category/513) category on OpenHealthHub, and I have [requested a dedicated AngelSensor category be created](https://www.openhealthhub.org/t/open-hardware-category/513) therein.

**Comment by niqt** [comment]
Ok, good idea, when the category is created we add the link on the wiki

**Comment by brylie** [comment]
OK, for now, lets just use the [Open Medical Hardware](https://www.openhealthhub.org/t/open-hardware-category/513) category until we have more discussion. That is the recommendation of the OpenHealthHub maintainer, since the Open Medical Hardware category is quiet right now.

**Comment by Flu-Ger** [comment]
done

**Comment by brylie** [comment]
Jep jep!
