### ISSUE TITLE
AngelSensor turns off

### ISSUE THREAD

**Issue by urgas9** [AngelSensorCommunityEdition/angel-sdk-community#4]
I know that this is not repo related issue, but I will try to find an answer here, as nobody from the official developers responds.

I am looking for a solution to read AngelSensor's data on demand, throughout the day via a background service. The problem is that my wristband goes off after there are no active Bluetooth connections. Does anyone have a solution for that (e.g. always turned on firmware, Android code to keep the wristband on)?

Thank you very much!

**Comment by Flu-Ger** [comment]
You are kinda in luck.
Download the official app from googlePlay or AppleStore and flash latest firmware.
Bluetooth should then be turned on all the time.
But then you have no chance to turn it off, so I haven't tested it personally...

**Comment by urgas9** [comment]
Thanks. But where can I find the latest firmware?

**Comment by Flu-Ger** [comment]
Only the official apps in the respective stores have the firmware update feature, we therefore don't know how the update works, or where the firmware is actually located.
But when you install their app (not github), it will be fairly obvious on how to do it.

**Comment by mbaskaya** [comment]
http://www.angelsensor.com/firmware/
You should download DANIEL029.hex , transfer it to your phone storage and then update it from the app with that file.

**Comment by vpejovic** [comment]
Hi, after finding this thread I flashed my wristband with the latest firmware through the Angel Sensor app. No errors were reported during the process. However, now I don't see the wristband, neither through the app, nor via phone's Bluetooth sensing. Playing with the wristbands button doesn't seem to help either. Did anyone experience anything similar? Is there a way to factory reset the wristband? Thanks.

**Comment by mbaskaya** [comment]
Our wristband worked properly after flashing DANIEL029.hex, so I have no idea why that might have been. Pressing the button for 10 seconds will reset the wristband but I don't believe it is a factory reset, just erases memory I suppose. Maybe some charging issue you having? Good Luck.

**Comment by vpejovic** [comment]
Great, thanks a lot for the advice, connecting to the wristband works after the reset! I didn't know about the 10-second reset option.
