### ISSUE TITLE
Add support for Angel Sensor in GadgetBridge?

### ISSUE THREAD

**Issue by ldidry** [AngelSensorCommunityEdition/angel-sdk-community#6]
[GadgetBridge](https://github.com/Freeyourgadget/Gadgetbridge) is a multi-device smart band free/libre application, allowing to use some proprietary hardware like MiBand without their usually proprietary app (and sometimis even worse, their proporietary server).

I think it would make sense for the Angel Sensor community to contact them and ask and help them to add Angel Sensor support in GadgetBridge.

The Angel Sensor app… well, kinda sucks. Gadgetbridge seems to be a dynamic project which could help Angel Sensor users to use their hardware.

What do you think?

**Comment by Flu-Ger** [comment]
There is already an [open issue](https://github.com/Freeyourgadget/Gadgetbridge/issues/310) there.
To sum it up: he, too didn't get the Health Journal to work and just for the live readings the support doesn't seem worth it.
But you can get his [repository](https://github.com/cellscape/Gadgetbridge), he has a branch for AngelSensor.

**Comment by ldidry** [comment]
Ho! Sorry, I didn't saw the issue. Thank you for the URLs 👍
